AddEventHandler('esx:playerLoaded', function(source)
	TriggerEvent('esx_license:getLicenses', source, function(licenses)
		TriggerClientEvent('hex_policejob:zaladujlicke', source, licenses)
	end)
end)

RegisterServerEvent('hex_policejob:waterunit')
AddEventHandler('hex_policejob:waterunit', function(target2)
    TriggerEvent('esx_license:addLicense', target2, 'waterunit', function()
		TriggerEvent('esx_license:getLicenses', target2, function(licenses)
			TriggerClientEvent('hex_policejob:zaladujlicke', target2, licenses)
		end)
	end)
end)

RegisterServerEvent('hex_policejob:asu')
AddEventHandler('hex_policejob:asu', function(target2)
    TriggerEvent('esx_license:addLicense', target2, 'asu', function()
		TriggerEvent('esx_license:getLicenses', target2, function(licenses)
			TriggerClientEvent('hex_policejob:zaladujlicke', target2, licenses)
		end)
	end)
end)

RegisterServerEvent('hex_policejob:haw')
AddEventHandler('hex_policejob:haw', function(target)
    TriggerEvent('esx_license:addLicense', target, 'haw', function()
		TriggerEvent('esx_license:getLicenses', target, function(licenses)
			TriggerClientEvent('hex_policejob:zaladujlicke', target, licenses)
		end)
	end)
end)